-- +migrate Up
ALTER TABLE users ADD COLUMN version INT NOT NULL DEFAULT 1;
ALTER TABLE projects ADD COLUMN version INT NOT NULL DEFAULT 1;
ALTER TABLE issues ADD COLUMN version INT NOT NULL DEFAULT 1;
ALTER TABLE sprints ADD COLUMN version INT NOT NULL DEFAULT 1;
ALTER TABLE milestones ADD COLUMN version INT NOT NULL DEFAULT 1;
ALTER TABLE labels ADD COLUMN version INT NOT NULL DEFAULT 1;

-- +migrate Down
ALTER TABLE labels DROP COLUMN IF EXISTS version;
ALTER TABLE milestones DROP COLUMN IF EXISTS version;
ALTER TABLE sprints DROP COLUMN IF EXISTS version;
ALTER TABLE issues DROP COLUMN IF EXISTS version;
ALTER TABLE projects DROP COLUMN IF EXISTS version;
ALTER TABLE users DROP COLUMN IF EXISTS version;
